### PR TITLE
Added translation to the exercise module

### PR DESCRIPTION
**Pull request by martinheidegger**
Part of [translating the workshopper module](https://github.com/rvagg/workshopper/pull/74) is that exercise also needs some translation. This should be merged at the same time as the workshopper module.

### CODE REVIEW

**Comment by rvagg** [comment]
@martinheidegger in future, don't version bump in pull requests please, that should be for the person responsible for the release

**Comment by martinheidegger** [comment]
@rvagg Will do, just wanted to ease your load.

**Comment by rvagg** [comment]
@martinheidegger FYI, one of the reasons for this is that I use `npm version` which makes a git tag and signs it, I can't do it over the top of an existing version

**Comment by martinheidegger** [comment]
Thanks, didn't know that.

**Pull request merged**
